spring:
  application:
    name: forge
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o

forge:
  prompt: "Based on the following flaticon, generate a prompt focusing on its style, color palette, and mood. Do not reference the specific object depicted. Instead, create the description in a templated format where {VERTICAL} can be replaced by any object to generate a new image with the same style. The prompt should be detailed enough to be used with the DALL-E API to generate icons for different product category. Please format the prompt with words like 'should' 'must' may' etc. Each guideline must be on line breaks to ensure readability and modularity of the prompt."
  verticals:
    - "Telephone"
    - "Television"
    - "Four"
  outputDirectory: "classpath:/images"
