spring:
  application:
    name: forge
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o

forge:
  prompt: "Generate a picure of a dog."
  verticals:
    - "Telephone"
    - "Television"
    - "Four"
  outputDirectory: "src/main/resources/images"

logging:
  level:
    root: INFO
    com.scezen.forge: INFO
