spring:
  application:
    name: forge
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o

forge:
  prompt: |
    Create a flat icon of a {VERTICAL} that strictly adheres to the following guidelines:

    - The icon should be in a modern, minimalist style with clean and simple lines.
    - The icon must be integrated inside a circle with a central focus on the {VERTICAL}.
    - Use a soft color palette consisting primarily of shades of green and off-white.
    - The image must not have any shadows or drop shadows of any kind.
    - The design may include small, decorative elements such as leaves.
    - The overall mood must be fresh and eco-friendly, evoking a sense of calm and simplicity.
    - The background color must be full white without any gradient or texture.
    - There must be absolutely no shadows or drop shadows.
    - No design elements should extend beyond the circle.
  verticals:
    - "Cellphone"
    - "Television"
    - "Oven"
  outputDirectory: "src/main/resources/images"